---
apiVersion: v1
kind: Service
metadata:
  name: microapp
  namespace: poc
  labels:
    app: microapp
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: microapp